<a href="https://colab.research.google.com/github/adityajain2407/ref-dav-3/blob/main/aj_ref_chisquared_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import chisquare # Statistical test (chistat, pvalue)
from scipy.stats import chi2
from scipy.stats import chi2_contingency

# Coin toss

In [ ]:
# H0: Coin is fair
# Ha: Coin is biased
alpha = 0.05
chi_stat, p_value = chisquare(
    [28, 22], # Observed or actual
    [25, 25], # Expected
)
print(p_value)
print(chi_stat)
if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to reject H0")
    print("Coin is fair")

0.3961439091520741
0.72
Fail to reject H0
Coin is fair


In [ ]:
(28 - 25)**2/25 + (22 - 25)**2 /25 # chi2stat

0.72

In [ ]:
1 - chi2.cdf(0.72, df=1) #finding p-=value this way using chi2 stat value

0.3961439091520741

In [ ]:
chi2.ppf(0.95, df=1) #finding critical value of chisquare: with 95% confidence we can reject null hypo if chisuare value is greater than 3.84
#so if more chisquare values are on the lower side, that means the differences square are small - so null hupo is supported

3.841458820694124

In [ ]:
(45 - 25)**2/25 + (5 - 25)**2 /25 # chi2stat

32.0

In [ ]:
1 - chi2.cdf(32, df=1)

1.5417257914762672e-08

In [ ]:
chisquare(
    [45, 5],
    [25, 25]
)

Power_divergenceResult(statistic=32.0, pvalue=1.5417257900280013e-08)

In [ ]:
1 - chi2.cdf(3.84, df=1) #3.84 is threshold for chisquare value: left of it, p val is large, right of it - small

0.05004352124870515

# Gender Vs Offline and Online

Testing independence with chi2_contingency

In [ ]:
# H0: Gender and preference are independent
# H0: Preference depends on gender
observed = [
    [527, 72],
    [206, 102],
]

chi_stat, p_value, df, exp_freq = chi2_contingency(observed) # chi_stat, p_value, df, expected values
print(chi_stat)
print(p_value)
print(df)
print(exp_freq)

if p_value < 0.05:
    print("Reject H0")

57.04098674049609
4.268230756875865e-14
1
[[484.08710033 114.91289967]
 [248.91289967  59.08710033]]
Reject H0


# Aerofit

In [ ]:
df_aerofit = pd.read_csv("aerofit.csv")

In [ ]:
df_aerofit.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   KP281   18    Male         14        Single      3        4   29562    112
1   KP281   19    Male         15        Single      2        3   31836     75
2   KP281   19  Female         14     Partnered      4        3   30699     66
3   KP281   19    Male         12        Single      3        3   32973     85
4   KP281   20    Male         13     Partnered      4        2   35247     47

In [ ]:
gender_product = pd.crosstab(index=df_aerofit['Gender'],columns=df_aerofit['Product'])
gender_product

Product  KP281  KP481  KP781
Gender                      
Female      40     29      7
Male        40     31     33

In [ ]:
# H0: Gender does not impact buying of product
# Ha: Gender impacts product
chi_stat, p_value, df, exp_value = chi2_contingency(gender_product) # chi_stat, p_value, df, expected value
print(chi_stat)
print(p_value)
print(df)
print(exp_value)
if p_value < 0.05:
    print("Reject H0")
    print("Gender impacts product")

12.923836032388664
0.0015617972833158714
2
[[33.77777778 25.33333333 16.88888889]
 [46.22222222 34.66666667 23.11111111]]
Reject H0
Gender impacts product


In [ ]:
# If KP781 data is not there
# H0: Gender does not impact buying of product
# Ha: Gender impacts product
chi2_contingency([[40, 29], [40, 31]])

Chi2ContingencyResult(statistic=0.0005953595971967067, pvalue=0.9805335549105975, dof=1, expected_freq=array([[39.42857143, 29.57142857],
       [40.57142857, 30.42857143]]))